name: vpc-ci-dev-create

on:
  push:
    branches:
      - feat/setup-ci

env:
  AWS_ACCOUNT_NUMBER: 211125759162

# defaults:
#   run:
#     shell: bash
#     working-directory: ./iac/terraform/vpc
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ./iac/terraform/vpc

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: eu-central-1
          role-to-assume: arn:aws:iam::${{env.AWS_ACCOUNT_NUMBER}}:role/github-actions-role
          role-session-name: Session-GitHubActions

      - name: Get AWS Caller Identity
        run: |
          aws sts get-caller-identity --output json

  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        # with:
        #   path: ./iac/chart/

      # - name: Change directory
      #   run: cd ./iac/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: eu-central-1
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_NUMBER }}:role/github-actions-role
          role-session-name: Session-GitHubActions

      - name: Login to Amazon ECR
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/t5i1x5v9

      - name: Build, Tag and Push Docker Image
        run: |
          docker build -t demo-image:latest -f demo-app/Dockerfile .
          docker tag demo-image:latest public.ecr.aws/t5i1x5v9/demo-image:latest
          docker push public.ecr.aws/t5i1x5v9/demo-image:latest

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          path: ./iac/

      - name: Change directory
        run: cd ./iac/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: eu-central-1
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_NUMBER }}:role/github-actions-role
          role-session-name: Session-GitHubActions

      # Add your deployment steps here
      # For example:
      - name: Deploy to Kubernetes
        run: |
          # Run your deployment commands here
          echo "Deploying to Kubernetes..."
